<?php
/**
 * @file
 * indies_research_stories.features.inc
 */

/**
 * Implements hook_ctools_plugin_api().
 */
function indies_research_stories_ctools_plugin_api($module = NULL, $api = NULL) {
  if ($module == "bean_admin_ui" && $api == "bean") {
    return array("version" => "5");
  }
  if ($module == "ds" && $api == "ds") {
    return array("version" => "1");
  }
  if ($module == "field_group" && $api == "field_group") {
    return array("version" => "1");
  }
}
